### ISSUE TITLE
Code sandbox example is breaking if we set default count value to 1

### ISSUE THREAD

**Issue by kamaljitSharma21** [Roxiler/react-fb-image-video-grid#4]
In the code sandbox of Demo section if we set default value of count to 1 at that point it breaks the application

<img width="1259" alt="Screenshot 2022-06-15 at 5 54 51 PM" src="https://user-images.githubusercontent.com/98891986/173826652-cd97b55b-f78c-4213-8fed-3bc06ed295be.png">

**Comment by sai6855** [comment]
code sand box example is working now
